name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
        - uses: actions/checkout@v4
        
        - uses: 'google-github-actions/auth@v2'
          with:
            workload_identity_provider: 'projects/638956850939/locations/global/workloadIdentityPools/github/providers/my-repo'
            service_account: 'github-deploy@datafi-415911.iam.gserviceaccount.com'

        - name: Deploy to Cloud Run
          id: deploy
          uses: 'google-github-actions/deploy-cloudrun@v2'
          with:
            service: 'dashboards-grpc'
            region: 'europe-north1'
            # NOTE: If required, update to the appropriate source folder
            source: ./

        # If required, use the Cloud Run url output in later steps
        - name: Show Output
          run: echo ${{ steps.deploy.outputs.url }}


