name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
        - uses: actions/checkout@v4
        
        - uses: 'google-github-actions/auth@v2'
          with:
            project_id: 'datafi-415911'
            workload_identity_provider: 'projects/638956850939/locations/global/workloadIdentityPools/github/providers/my-repo'

